// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "gcap-20181003104601--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://gcap-20181003104601--hostingbucket.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:25f7c9cf-05ca-49fb-98f6-e2c0925bbd8f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Xg24S4Nma",
    "aws_user_pools_web_client_id": "1711hu6sa6m2dks2dif7bpodm2",
    "aws_appsync_graphqlEndpoint": "https://prulcoat45fqvo74zq2eudk5ue.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
